package ticketsreservation;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Dialog.ModalExclusionType;
import javax.swing.JList;
import javax.swing.JScrollPane;


public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
    	setAutoRequestFocus(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {
    	
        
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHour = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnshowstatistics = new javax.swing.JButton();
        btnshowstatistics.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		 Connection conn = null;
        		 Statement stmt = null;
        	        ResultSet rs = null;
        	        DefaultListModel listModel = new DefaultListModel();
        	        try
        	        {

        	            Class.forName("com.mysql.jdbc.Driver").newInstance();
        	            String connectionUrl = "jdbc:mysql://localhost:3306/sunaulies";
        	            String connectionUser = "root";
        	            String connectionPassword = "root";
        	            conn = DriverManager.getConnection(connectionUrl, connectionUser,
        	                connectionPassword);
        	            stmt = conn.createStatement();
        	            rs = stmt.executeQuery("SELECT * FROM theseisun ");
        	            
        	            while (rs.next())
        	            {

        	            	 String name = rs.getString("theseisvip");
        	                 String name1 = rs.getString("theseisaples");
        	                 String name2 =rs.getString("id");
        	                

        	                 listModel.addElement(name2+ "          "+name +"      "+ name1);
        	                 
        	                
        	                //String name1 = rs.getString("theseis vip");
            	            //listModel.addElement(name1);
        	                

        	            }
        	          
        	            //playsList = new JList(listModel);

        	        }
        	        catch (Exception e)
        	        {
        	            e.printStackTrace();
        	        }
        		
        	        list.setModel(listModel);
        	        scrollPane.setViewportView(list);
        		
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u0394\u03B9\u03B1\u03C7\u03B5\u03B9\u03C1\u03B9\u03C3\u03C4\u03B7\u03C2");

        jLabel1.setText("\u038C\u03BD\u03BF\u03BC\u03B1");

        jLabel2.setText("\u038F\u03C1\u03B1");

        btnRegister.setText("\u0395\u03BA\u03C7\u03CE\u03C1\u03B7\u03C3\u03B7");
        btnshowstatistics.setText("\u03A3\u03C4\u03B1\u03C4\u03B9\u03C3\u03C4\u03B9\u03BA\u03AC");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        
        scrollPane = new JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(48)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
        					.addGap(40)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtHour, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtName, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(btnRegister))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnshowstatistics)
        			.addGap(517))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(105)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(1032, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE)
        			.addGap(24)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnRegister)
        				.addComponent(btnshowstatistics))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        list = new JList();
        scrollPane.setViewportView(list);
        getContentPane().setLayout(layout);

        pack();
        
    }  
        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    	
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
		
	try
	{
	
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		String connectionUrl = "jdbc:mysql://localhost:3306/sunaulies";
		String connectionUser = "root";
		String connectionPassword = "root";
		conn = DriverManager.getConnection(connectionUrl, connectionUser,
		connectionPassword);
		stmt = conn.createStatement();
		String name= txtName.getText();
		String hour= txtHour.getText();
		
		
		String lastid ="select * from plays ";
		rs=stmt.executeQuery(lastid);
		if(rs.last()){
			int id = rs.getInt("id");
			
			id++;
		
		String strSql1 = "INSERT INTO plays (id,name) values('"+id+"','"+name+"')";
				stmt.executeUpdate(strSql1);
				
				
		String strSql2 = "INSERT INTO time (id,time) values('"+id+"', '"+hour+"')";
				stmt.executeUpdate(strSql2);
		
		String strSql3 = "INSERT INTO theseisun (id) values('"+id+"')";
				stmt.executeUpdate(strSql3);
				stmt.close();
				JOptionPane.showMessageDialog(null, "Η καταχώρηση  έγινε με επιτυχία ");
		
		}
		
	}
	catch (Exception e)
	{
	e.printStackTrace();
	}

	

        
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnshowstatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtHour;
    private javax.swing.JTextField txtName;
    private JScrollPane scrollPane;
    private JList list;
}
