/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ticketsreservation;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.DefaultListCellRenderer;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JButton;
import java.awt.Color;
import java.sql.*;

public class SeatSelection extends javax.swing.JFrame {

    /**
     * Creates new form SeatSelection
     */
    public SeatSelection(String play, String selectedHour) {
    	setForeground(Color.BLACK);
    	setBackground(Color.BLACK);
        initComponents(play);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String play) {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {  
        	SeatSelection.this.setVisible(false);
           
           
        		
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Εκδοτήρια");

        jList1.setModel(new javax.swing.AbstractListModel() {
        	
            String[] strings = { "1", "12", "23", "34"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "2", "13", "24", "35"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "3", "14", "25", "36"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "5", "16", "27", "38"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "6", "17", "28", "39"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList7);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Αριστερά");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Κέντρο");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Δεξιά");

        jLabel4.setText("Θέσεις VIP:");

        jButton2.setText("Κράτηση απλη");

        jButton3.setText("Εκτύπωση");
        
        JCheckBox chckbxNewCheckBox = new JCheckBox("\u0391\u03C0\u03BB\u03AE \u0395\u03AF\u03C3\u03BF\u03B4\u03BF\u03C2");
        chckbxNewCheckBox.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if (chckbxNewCheckBox.isSelected()){
        			jList1.setVisible(false);
        		jList2.setVisible(false);
        		jList3.setVisible(false);
        		jList4.setVisible(false);
        		jList5.setVisible(false);
        		jList6.setVisible(false);
        		jList7.setVisible(false);
        		jList8.setVisible(false);
        		jList9.setVisible(false);
        		jList10.setVisible(false);
        		jList11.setVisible(false);
        		jLabel1.setVisible(false);
        		jLabel2.setVisible(false);
        		jLabel3.setVisible(false);
        		
        		} else{
        			jList1.setVisible(true);
        			jList2.setVisible(true);
            		jList3.setVisible(true);
            		jList4.setVisible(true);
            		jList5.setVisible(true);
            		jList6.setVisible(true);
            		jList7.setVisible(true);
            		jList8.setVisible(true);
            		jList9.setVisible(true);
            		jList10.setVisible(true);
            		jList11.setVisible(true);
            		jLabel1.setVisible(true);
            		jLabel2.setVisible(true);
            		jLabel3.setVisible(true);
        		}
        		 
        		
        			
        		}
        		
        			
        		
        	
        });
       jButton2.addActionListener(new ActionListener() {
        	private int sum2,sum3;
        	private int clicked;
			public void actionPerformed(ActionEvent e) {
				Connection conn = null;
		        Statement stmt = null;
		        ResultSet rs = null;
				
			try
			{
			
				Class.forName("com.mysql.jdbc.Driver").newInstance();
				String connectionUrl = "jdbc:mysql://localhost:3306/sunaulies";
				String connectionUser = "root";
				String connectionPassword = "root";
				conn = DriverManager.getConnection(connectionUrl, connectionUser,
				connectionPassword);
				stmt = conn.createStatement();
				
				if (chckbxNewCheckBox.isSelected()){
					
					/*rs = stmt.executeQuery("SELECT * FROM theseisun");
    	             if (rs.last()); 
    	             String name = rs.getString("theseisaples");					 					 
    	             int sum = Integer.parseInt(name);
					  sum++;
					
					String strSql1 = "INSERT INTO theseisun (theseisaples) values('"+sum+"')";
					stmt.executeUpdate(strSql1);
	        		System.out.println(+sum);*/
	        		
					
					sum2=Integer.parseInt(play.replaceAll("[\\D]", ""));
					
					String name ="select theseisaples from theseisun where id= '"+ sum2 +"'";
					ResultSet tade=stmt.executeQuery(name);
					if (tade.last()) {
					    String val = tade.getString("theseisaples");
					    System.out.println(val);
					    sum3=Integer.parseInt(val.replaceAll("[\\D]", ""));
					    clicked= sum3;
						clicked++;
						System.out.print(clicked);
											
					
						String strSql1 =  "update theseisun set theseisaples = "+clicked+" where id = '"+sum2+"' ";
						stmt.executeUpdate(strSql1);
					
						JOptionPane.showMessageDialog(null, "Μία θεση απλή κρατήθηκε");
					
			
			
					}
				
				}
			}
				
				
				
			
				
			
			catch (Exception e1)
			{
			e1.printStackTrace();
			}
				
					
				
				
						
					
					

					
				
				
        		
        	}
        });
      
        JCheckBox chckbxVip = new JCheckBox("VIP");
        JButton btnVip = new JButton("Κράτηση VIP");
        btnVip.addActionListener(new ActionListener() {
        	 private int clicked;
        	public void actionPerformed(ActionEvent arg0) {
        		Connection conn = null;
		        Statement stmt = null;
		        ResultSet rs = null;
				
			try
			{
			
				Class.forName("com.mysql.jdbc.Driver").newInstance();
				String connectionUrl = "jdbc:mysql://localhost:3306/sunaulies";
				String connectionUser = "root";
				String connectionPassword = "root";
				conn = DriverManager.getConnection(connectionUrl, connectionUser,
				connectionPassword);
				stmt = conn.createStatement();
				int sum ,sum1 = 0;
				
				if (chckbxVip.isSelected()){
					
					sum=Integer.parseInt(play.replaceAll("[\\D]", ""));
					
					String name ="select theseisvip from theseisun where id= '"+sum+"'";
					ResultSet tade=stmt.executeQuery(name);
					if (tade.last()) {
					    String val = tade.getString("theseisvip");
					   
					    sum1=Integer.parseInt(val.replaceAll("[\\D]", ""));
					    clicked= sum1;
					    if (clicked<45){
						clicked++;
						
												
						String strSql1 =  "update theseisun set theseisvip = "+clicked+" where id = '"+sum+"' ";
						stmt.executeUpdate(strSql1);
						JOptionPane.showMessageDialog(null, "Μία θεση VIP κρατήθηκε");
					    }else{
					    	JOptionPane.showMessageDialog(null, "Δεν υπαρχουν αλλες κενες θεσεις");
					    	System.exit(0);
					    	
					    }
					}
					
					
	        		
	        		
			
			
					
				
				
				
				
				
			
				}
			     }
			catch (Exception e1)
			{
			e1.printStackTrace();
			}
        		
        	}
        });
        
       
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel1)
        									.addGap(167)
        									.addComponent(jLabel2))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        									.addGap(100)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(chckbxVip, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        											.addPreferredGap(ComponentPlacement.UNRELATED)
        											.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        											.addPreferredGap(ComponentPlacement.RELATED)
        											.addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        										.addComponent(btnVip))
        									.addGap(6)
        									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        											.addGap(79)
        											.addComponent(jScrollPane11, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        										.addComponent(jButton3)))))
        						.addComponent(jButton2))
        					.addGap(24)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel3)
        						.addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        					.addGap(39)
        					.addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(261)
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(chckbxNewCheckBox, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane11, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        								.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(chckbxNewCheckBox)
        								.addComponent(chckbxVip))))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(jButton2)
        							.addComponent(jButton3))
        						.addComponent(btnVip))))
        			.addContainerGap())
        );
        jList9 = new javax.swing.JList();
        jScrollPane9.setViewportView(jList9);
        
                jList9.setModel(new javax.swing.AbstractListModel() {
                    String[] strings = { "11", "22", "33", "44"};
                    public int getSize() { return strings.length; }
                    public Object getElementAt(int i) { return strings[i]; }
                });
        jList10 = new javax.swing.JList();
        jScrollPane10.setViewportView(jList10);
        
                jList10.setModel(new javax.swing.AbstractListModel() {
                    String[] strings = { "10", "21", "32", "43"};
                    public int getSize() { return strings.length; }
                    public Object getElementAt(int i) { return strings[i]; }
                });
        jList11 = new javax.swing.JList();
        jScrollPane11.setViewportView(jList11);
        
                jList11.setModel(new javax.swing.AbstractListModel() {
                    String[] strings = { "9", "20", "31", "42"};
                    public int getSize() { return strings.length; }
                    public Object getElementAt(int i) { return strings[i]; }
                });
        jList8 = new javax.swing.JList();
        jScrollPane8.setViewportView(jList8);
        
                jList8.setModel(new javax.swing.AbstractListModel() {
                    String[] strings = { "8", "19", "30", "41"};
                    public int getSize() { return strings.length; }
                    public Object getElementAt(int i) { return strings[i]; }
                });
        jList6 = new javax.swing.JList();
        jScrollPane6.setColumnHeaderView(jList6);
        
                jList6.setModel(new javax.swing.AbstractListModel() {
                    String[] strings = { "7", "18", "29", "40"};
                    public int getSize() { return strings.length; }
                    public Object getElementAt(int i) { return strings[i]; }
                });
        jList4 = new javax.swing.JList();
        jScrollPane4.setViewportView(jList4);
        
                jList4.setModel(new javax.swing.AbstractListModel() {
                    String[] strings = { "4", "15", "26", "37"};
                    public int getSize() { return strings.length; }
                    public Object getElementAt(int i) { return strings[i]; }
                });
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatSelection("Default", "Default").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList10;
    private javax.swing.JList jList11;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JList jList8;
    private javax.swing.JList jList9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
}
